export const EXTENSION_NAME = 'SillyTavern-Card-Crafter';
export const MODULE_NAME = 'cardCrafter';
export const VERSION = '1.0.2';
export const DISPLAY_NAME = 'Card Crafter';

export const TABS = [
    { id: 'generate', label: 'Generate', icon: 'fa-wand-magic-sparkles' },
    { id: 'analyze', label: 'Analyze', icon: 'fa-gauge-high' },
    { id: 'remediate', label: 'Remake', icon: 'fa-screwdriver-wrench' },
    { id: 'settings', label: 'Settings', icon: 'fa-gear' },
];

export const GENERATION_TYPES = [
    { id: 'character', label: 'Character', hint: 'A full V2 character card' },
    { id: 'lorebook', label: 'Lorebook', hint: 'World info entries for a setting' },
    { id: 'persona', label: 'Persona', hint: 'A {{user}} persona, not a bot' },
];

export const DEFAULT_SETTINGS = {
    slopThreshold: 55,
    enableAiSlopAnalysis: false,
    defaultCreativity: 45,
    maxResponseTokens: 3500,
    autoImportLorebook: true,
    compactMobile: true,
    creatorName: '',
};

export const SLOP_TROPES = [
    { phrase: 'defies description', weight: 8 },
    { phrase: 'air of mystery', weight: 6 },
    { phrase: "can't help but", weight: 5 },
    { phrase: 'cannot help but', weight: 5 },
    { phrase: 'a mix of', weight: 3 },
    { phrase: 'a mixture of', weight: 3 },
    { phrase: 'yet somehow', weight: 5 },
    { phrase: 'despite her', weight: 4 },
    { phrase: 'despite his', weight: 4 },
    { phrase: 'lingering scent', weight: 7 },
    { phrase: 'scent of', weight: 3 },
    { phrase: 'smirk playing', weight: 7 },
    { phrase: 'playful smirk', weight: 5 },
    { phrase: 'knowing smirk', weight: 5 },
    { phrase: 'orbs', weight: 8 },
    { phrase: 'doe eyes', weight: 4 },
    { phrase: 'plump lips', weight: 7 },
    { phrase: 'full lips', weight: 3 },
    { phrase: 'hourglass figure', weight: 7 },
    { phrase: 'ample bosom', weight: 8 },
    { phrase: 'supple', weight: 4 },
    { phrase: 'alabaster', weight: 5 },
    { phrase: 'porcelain skin', weight: 6 },
    { phrase: 'not like other', weight: 8 },
    { phrase: 'touch her and you die', weight: 9 },
    { phrase: 'touch him and you die', weight: 9 },
    { phrase: 'will kill anyone who', weight: 7 },
    { phrase: 'broken bird', weight: 8 },
    { phrase: 'emotionally unavailable', weight: 3 },
    { phrase: 'dominant yet submissive', weight: 9 },
    { phrase: 'submissive yet dominant', weight: 9 },
    { phrase: 'tsundere', weight: 3 },
    { phrase: 'yandere', weight: 3 },
    { phrase: 'kuudere', weight: 3 },
    { phrase: 'dandere', weight: 3 },
    { phrase: 'unfiltered', weight: 6 },
    { phrase: 'uncensored', weight: 6 },
    { phrase: 'no restrictions', weight: 6 },
    { phrase: 'as an ai', weight: 10 },
    { phrase: 'you are to roleplay', weight: 8 },
    { phrase: 'you will roleplay', weight: 8 },
    { phrase: 'i want you to roleplay', weight: 8 },
    { phrase: 'note to the ai', weight: 9 },
    { phrase: 'note to ai', weight: 9 },
    { phrase: '[system', weight: 6 },
    { phrase: 'do not break character', weight: 5 },
    { phrase: 'never break character', weight: 5 },
    { phrase: 'stay in character', weight: 4 },
    { phrase: 'nsfw allowed', weight: 5 },
    { phrase: 'this character is', weight: 3 },
    { phrase: 'char is a', weight: 3 },
    { phrase: '{{char}} is a', weight: 3 },
    { phrase: 'speaks in a', weight: 2 },
    { phrase: 'voice like honey', weight: 6 },
    { phrase: 'voice like silk', weight: 6 },
    { phrase: 'danger and allure', weight: 7 },
    { phrase: 'beauty and danger', weight: 6 },
    { phrase: 'intoxicating', weight: 4 },
    { phrase: 'enigmatic', weight: 3 },
    { phrase: 'ethereal', weight: 3 },
    { phrase: 'otherworldly beauty', weight: 7 },
    { phrase: 'curves in all the right', weight: 8 },
    { phrase: 'lithe', weight: 3 },
    { phrase: 'willowy', weight: 3 },
    { phrase: 'petite frame', weight: 4 },
    { phrase: 'towering over', weight: 3 },
    { phrase: 'pins you', weight: 4 },
    { phrase: 'looks down at you', weight: 3 },
    { phrase: 'narrows (his|her|their) eyes', weight: 3, regex: true },
    { phrase: 'bites (his|her|their) lip', weight: 5, regex: true },
    { phrase: 'chews on (his|her|their) lip', weight: 5, regex: true },
    { phrase: 'heart-shaped face', weight: 4 },
    { phrase: 'button nose', weight: 3 },
    { phrase: 'raven hair', weight: 4 },
    { phrase: 'cascading', weight: 3 },
    { phrase: 'tumble down', weight: 4 },
    { phrase: 'down to (her|his|their) waist', weight: 4, regex: true },
    { phrase: 'perfectly proportioned', weight: 7 },
    { phrase: 'impossibly', weight: 4 },
    { phrase: 'dangerously attractive', weight: 6 },
    { phrase: 'makes you feel', weight: 4 },
    { phrase: 'you can\'t help', weight: 5 },
    { phrase: 'the air around', weight: 4 },
    { phrase: 'aura of', weight: 4 },
    { phrase: 'personality: kind', weight: 5 },
    { phrase: 'kind, caring', weight: 6 },
    { phrase: 'sweet and innocent', weight: 5 },
    { phrase: 'innocent yet', weight: 5 },
    { phrase: 'mysterious past', weight: 6 },
    { phrase: 'tragic backstory', weight: 5 },
    { phrase: 'dark secret', weight: 4 },
    { phrase: 'hidden depths', weight: 5 },
    { phrase: 'more than meets the eye', weight: 6 },
    { phrase: 'whisper-soft', weight: 4 },
    { phrase: 'husky voice', weight: 3 },
    { phrase: 'low, gravelly', weight: 4 },
    { phrase: 'like velvet', weight: 5 },
    { phrase: 'goddess', weight: 3 },
    { phrase: 'adhds', weight: 2 },
    { phrase: 'uwu', weight: 4 },
    { phrase: 'owo', weight: 4 },
    { phrase: 'senpai', weight: 2 },
    { phrase: 'kawaii', weight: 2 },
    { phrase: 'desu', weight: 3 },
    { phrase: 'loves everyone equally', weight: 5 },
    { phrase: 'will do anything for you', weight: 6 },
    { phrase: 'obsessed with {{user}}', weight: 5 },
    { phrase: 'immediately attracted', weight: 6 },
    { phrase: 'love at first sight', weight: 5 },
    { phrase: 'soulmate', weight: 4 },
    { phrase: 'fated', weight: 3 },
    { phrase: 'the chosen one', weight: 5 },
    { phrase: 'only you can', weight: 5 },
    { phrase: 'in this world,', weight: 3 },
    { phrase: 'welcome to my world', weight: 4 },
    { phrase: 'let me tell you about myself', weight: 6 },
    { phrase: 'allow me to introduce', weight: 5 },
];

export const FILLER_PHRASES = [
    'it is important to note',
    'in order to',
    'due to the fact',
    'at the end of the day',
    'needless to say',
    'as mentioned above',
    'as previously stated',
    'in conclusion',
    'overall,',
    'furthermore',
    'moreover',
    'that being said',
    'when it comes to',
    'the fact that',
    'a sense of',
    'a hint of',
    'a touch of',
    'something about',
    'there is something',
    'one could say',
    'it can be said',
    'known to be',
    'tends to be',
    'often found',
];

export const REQUIRED_CHAR_FIELDS = [
    'name',
    'description',
    'personality',
    'scenario',
    'first_mes',
    'mes_example',
];
